---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: freebsd-9.3
    driver:
      box: opscode-freebsd-9.3
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-9.3_chef-provisionerless.box
  # - name: ubuntu-14.04
  # - name: centos-7.1

suites:
  - name: master
    run_list:
      - recipe[smokeping::master]
    attributes:
  - name: slave
    run_list:
      - recipe[smokeping::slave]
    attributes:
