name 'smokeping'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures smokeping'
long_description 'Installs/Configures smokeping'
version '0.1.0'
